/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
          "primary-fixed-dim": "#8885ff",
          "on-secondary-fixed-variant": "#005969",
          "on-primary": "#f4f1ff",
          "tertiary-fixed": "#c0a0ff",
          "surface-container": "#e5e9eb",
          "surface-variant": "#d9dde0",
          "tertiary-container": "#c0a0ff",
          "surface-dim": "#d0d5d8",
          "surface-container-high": "#dfe3e6",
          "on-surface-variant": "#595c5e",
          "on-primary-container": "#14007e",
          "tertiary-dim": "#6411d5",
          "secondary-fixed": "#65e1ff",
          "outline": "#747779",
          "surface-container-low": "#eef1f3",
          "on-primary-fixed-variant": "#1a0099",
          "inverse-on-surface": "#9a9d9f",
          "surface-container-lowest": "#ffffff",
          "inverse-surface": "#0b0f10",
          "primary": "#4a40e0",
          "on-secondary": "#def7ff",
          "secondary": "#006576",
          "tertiary-fixed-dim": "#b48fff",
          "on-tertiary": "#f8f0ff",
          "outline-variant": "#abadaf",
          "surface-bright": "#f5f7f9",
          "on-tertiary-fixed-variant": "#4a00a4",
          "secondary-container": "#65e1ff",
          "on-primary-fixed": "#000000",
          "primary-dim": "#3d30d4",
          "on-error": "#ffefef",
          "secondary-fixed-dim": "#48d4f3",
          "inverse-primary": "#8582ff",
          "primary-container": "#9795ff",
          "tertiary": "#702ae1",
          "surface-container-highest": "#d9dde0",
          "on-tertiary-fixed": "#200051",
          "on-secondary-fixed": "#003a45",
          "primary-fixed": "#9795ff",
          "background": "#f5f7f9",
          "surface-tint": "#4a40e0",
          "error-dim": "#a70138",
          "error": "#b41340",
          "secondary-dim": "#005867",
          "on-error-container": "#510017",
          "error-container": "#f74b6d",
          "on-surface": "#2c2f31",
          "on-secondary-container": "#004f5d",
          "on-background": "#2c2f31",
          "on-tertiary-container": "#3f008e",
          "surface": "#f5f7f9"
      },
      "borderRadius": {
          "DEFAULT": "0.25rem",
          "lg": "0.5rem",
          "xl": "0.75rem",
          "full": "9999px"
      },
      "fontFamily": {
          "headline": ["Plus Jakarta Sans", "sans-serif"],
          "body": ["Inter", "sans-serif"],
          "label": ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}
