export default function AIAssistant() {
  return (
    <div className="flex-1 overflow-y-auto px-4 md:px-10 py-8 relative w-full h-full">
      {/* Hero Content */}
      <div className="mb-12">
        <header className="flex flex-col md:flex-row justify-between items-start md:items-end gap-6 mb-8">
          <div>
            <span className="text-[0.65rem] font-bold uppercase tracking-[0.2em] text-tertiary mb-2 block">Intelligence Suite</span>
            <h1 className="text-4xl font-extrabold font-headline tracking-tight text-on-surface">AI Productivity Assistant</h1>
          </div>
          <div className="flex gap-3">
            <button className="bg-surface-container-high px-6 py-2.5 rounded-full text-sm font-semibold flex items-center gap-2 hover:opacity-80 transition-all">
              <span className="material-symbols-outlined text-lg">history</span>
              Recent Sessions
            </button>
          </div>
        </header>

        {/* Action Cards (Asymmetric Bento Grid) */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-12">
          <div className="md:col-span-2 group relative overflow-hidden bg-gradient-to-br from-primary to-primary-dim p-8 rounded-xl text-on-primary">
            <div className="relative z-10 h-full flex flex-col justify-between">
              <div>
                <div className="w-12 h-12 rounded-xl bg-white/20 backdrop-blur-md flex items-center justify-center mb-6">
                  <span className="material-symbols-outlined text-2xl text-white" style={{ fontVariationSettings: "'FILL' 1" }}>auto_awesome</span>
                </div>
                <h3 className="text-2xl font-bold font-headline mb-2">Kinetic AI Chat</h3>
                <p className="text-on-primary/80 max-w-md text-sm leading-relaxed">Your collaborative partner for brainstorming, technical troubleshooting, and institutional knowledge retrieval.</p>
              </div>
              <div className="mt-8">
                <div className="bg-white/10 backdrop-blur-md p-2 rounded-full flex items-center gap-3 border border-white/10 focus-within:bg-white/20 transition-all">
                  <input className="bg-transparent border-none focus:ring-0 placeholder:text-white/60 text-sm flex-1 px-4 outline-none" placeholder="Ask Kinetic AI anything..." type="text"/>
                  <button className="bg-white text-primary w-10 h-10 rounded-full flex items-center justify-center hover:scale-105 transition-transform shrink-0">
                    <span className="material-symbols-outlined">send</span>
                  </button>
                </div>
              </div>
            </div>
            <div className="absolute top-0 right-0 w-64 h-64 bg-white/10 rounded-full -mr-20 -mt-20 blur-3xl"></div>
          </div>
          
          <div className="space-y-6">
            <button className="w-full text-left bg-surface-container-lowest p-6 rounded-xl hover:shadow-[0px_24px_48px_rgba(44,47,49,0.06)] transition-all group border border-outline-variant/10">
              <span className="material-symbols-outlined text-secondary mb-4 block text-3xl">map</span>
              <h4 className="font-bold text-on-surface mb-1">Generate Learning Roadmap</h4>
              <p className="text-xs text-on-surface-variant">Structured skill paths with curated resources.</p>
            </button>
            <button className="w-full text-left bg-surface-container-lowest p-6 rounded-xl hover:shadow-[0px_24px_48px_rgba(44,47,49,0.06)] transition-all group border border-outline-variant/10">
              <span className="material-symbols-outlined text-tertiary mb-4 block text-3xl">lightbulb</span>
              <h4 className="font-bold text-on-surface mb-1">Suggest Project Ideas</h4>
              <p className="text-xs text-on-surface-variant">Portfolio-ready concepts based on your stack.</p>
            </button>
          </div>
        </div>

        {/* Roadmap View (Main Task Result) */}
        <section className="bg-surface-container-low rounded-xl p-8">
          <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between mb-8 gap-4">
            <div className="flex items-center gap-4">
              <div className="w-10 h-10 rounded-lg bg-secondary flex items-center justify-center shrink-0">
                <span className="material-symbols-outlined text-white">alt_route</span>
              </div>
              <div>
                <h2 className="text-xl font-bold font-headline">Roadmap: Full-Stack Developer</h2>
                <p className="text-xs text-on-surface-variant font-medium">Generated by Kinetic Intelligence • High Confidence</p>
              </div>
            </div>
            <button className="shrink-0 text-primary text-sm font-bold flex items-center gap-2 hover:bg-primary/5 px-4 py-2 rounded-lg transition-colors">
              <span className="material-symbols-outlined text-lg">download</span>
              Export PDF
            </button>
          </div>

          <div className="space-y-12 relative before:absolute before:left-[19px] before:top-4 before:bottom-4 before:w-0.5 before:bg-surface-container-highest">
            {/* Phase 1 */}
            <div className="relative pl-14">
              <div className="absolute left-0 top-1 w-10 h-10 rounded-full bg-white border-4 border-secondary flex items-center justify-center z-10">
                <span className="text-xs font-bold text-secondary">01</span>
              </div>
              <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
                <div className="lg:col-span-1">
                  <h4 className="font-bold text-lg mb-2">Frontend Foundations</h4>
                  <p className="text-sm text-on-surface-variant leading-relaxed mb-4">Master the core building blocks of the modern web. Focus on semantics, responsiveness, and state.</p>
                  <div className="flex flex-wrap gap-2">
                    <span className="px-3 py-1 bg-secondary/10 text-secondary text-[10px] font-bold rounded-full uppercase tracking-wider">HTML5/CSS3</span>
                    <span className="px-3 py-1 bg-secondary/10 text-secondary text-[10px] font-bold rounded-full uppercase tracking-wider">Tailwind</span>
                    <span className="px-3 py-1 bg-secondary/10 text-secondary text-[10px] font-bold rounded-full uppercase tracking-wider">React</span>
                  </div>
                </div>
                <div className="lg:col-span-2 grid grid-cols-1 sm:grid-cols-2 gap-4">
                  <div className="bg-surface-container-lowest p-4 rounded-xl flex items-start gap-4 shadow-sm border border-transparent hover:border-outline-variant/10">
                    <img alt="Course" className="w-12 h-12 rounded-lg object-cover shrink-0" src="https://lh3.googleusercontent.com/aida-public/AB6AXuCLRnvrE6gsEpsAlhQ-1gIME2XU9uobnNDzck0wbm-VP4nxx5yiv4RcSLiO87nldBhd1yBvvTbf_n2hSbytIhCLk1sGMMhVLFjN1eGRS8TB5LIt8XYLK2hUVPocpbtS4MW7cDAs4i7UkIyUm6bEYSIatY9FCNSH8YFJ_TAPtRojtL6m7fd92VwCQJa_ZsGvUM-cRlS8LeLKhrFKVfSVBrI8JlUlaA5NzIfT7TeY8_-git9PV6bIMdTKF369iOKpGYirzPSkiFPidIY9" crossOrigin="anonymous"/>
                    <div>
                      <p className="text-xs font-bold mb-1">Advanced React Patterns</p>
                      <p className="text-[10px] text-on-surface-variant mb-2">8 hour deep-dive</p>
                      <a className="text-primary text-[10px] font-bold hover:underline" href="#">Start Learning →</a>
                    </div>
                  </div>
                  <div className="bg-surface-container-lowest p-4 rounded-xl flex items-start gap-4 shadow-sm border border-transparent hover:border-outline-variant/10">
                    <img alt="Project" className="w-12 h-12 rounded-lg object-cover shrink-0" src="https://lh3.googleusercontent.com/aida-public/AB6AXuDDE0dzJq5kjUqHmWxZVY21q_uIn_RWHDOk37FhfRJfYVHLe_S_bv-_uWJjzVNlCi3Iac3SzuQiQm80YylQFb9twGMHrVW4lQuR8Wg-S2vyIkdDW2a6BfNwtA_KNNefN_6HrSixqfNePwxsyvIOp6DGMSBFB-9NCXqhR08D1f2m2MZBN8naxeuDAXa9_u9X-iJl1ZvdB6WGrHIV0rQ0bzB0pvij-EUBQm5JHje9ds-d6CuW908HTCjEl6e26sHyC_NOpoj0VbfSgId0" crossOrigin="anonymous"/>
                    <div>
                      <p className="text-xs font-bold mb-1">Portfolio Dashboard</p>
                      <p className="text-[10px] text-on-surface-variant mb-2">Guided Project</p>
                      <a className="text-primary text-[10px] font-bold hover:underline" href="#">Build Project →</a>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            {/* Phase 2 */}
            <div className="relative pl-14 opacity-60 grayscale-[0.5]">
              <div className="absolute left-0 top-1 w-10 h-10 rounded-full bg-white border-4 border-surface-container-highest flex items-center justify-center z-10">
                <span className="text-xs font-bold text-on-surface-variant">02</span>
              </div>
              <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
                <div className="lg:col-span-1">
                  <h4 className="font-bold text-lg mb-2">Backend &amp; Databases</h4>
                  <p className="text-sm text-on-surface-variant leading-relaxed mb-4">Architecture and data persistence. Learn how to build scalable APIs and manage relational schemas.</p>
                  <div className="flex flex-wrap gap-2">
                    <span className="px-3 py-1 bg-surface-container-highest text-on-surface-variant text-[10px] font-bold rounded-full uppercase tracking-wider">Node.js</span>
                    <span className="px-3 py-1 bg-surface-container-highest text-on-surface-variant text-[10px] font-bold rounded-full uppercase tracking-wider">PostgreSQL</span>
                    <span className="px-3 py-1 bg-surface-container-highest text-on-surface-variant text-[10px] font-bold rounded-full uppercase tracking-wider">Redis</span>
                  </div>
                </div>
                <div className="lg:col-span-2 flex items-center justify-center bg-surface-container/50 rounded-xl border-2 border-dashed border-outline-variant/30 py-8">
                  <p className="text-xs font-medium text-on-surface-variant">Complete Phase 01 to unlock resources</p>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* Contextual NavigationDrawer (Floating Side Tool) - Only visible on XL screens to not overlap */}
      <div className="hidden xl:flex fixed right-6 top-[80px] bottom-6 w-80 bg-[#ffffff]/70 dark:bg-slate-900/70 backdrop-blur-xl rounded-2xl shadow-[0px_24px_48px_rgba(44,47,49,0.06)] p-6 flex-col z-50">
        <div className="mb-8">
          <span className="text-sm uppercase tracking-widest text-[#702ae1] font-['Plus_Jakarta_Sans'] font-semibold block mb-1">AI Insights</span>
          <p className="text-[10px] text-outline">Powered by Kinetic AI</p>
        </div>
        <div className="space-y-4 flex-1">
          <button className="w-full flex items-center gap-3 p-3 bg-[#702ae1]/10 text-[#702ae1] rounded-xl font-['Plus_Jakarta_Sans'] font-semibold transition-all">
            <span className="material-symbols-outlined">auto_awesome</span>
            <span className="text-sm">Summarize Page</span>
          </button>
          <button className="w-full flex items-center gap-3 p-3 text-[#2c2f31] dark:text-slate-400 hover:shadow-[0_0_15px_rgba(0,101,118,0.3)] transition-all font-['Plus_Jakarta_Sans'] font-semibold">
            <span className="material-symbols-outlined">edit_note</span>
            <span className="text-sm">Draft Message</span>
          </button>
          <button className="w-full flex items-center gap-3 p-3 text-[#2c2f31] dark:text-slate-400 hover:shadow-[0_0_15px_rgba(0,101,118,0.3)] transition-all font-['Plus_Jakarta_Sans'] font-semibold">
            <span className="material-symbols-outlined">plumbing</span>
            <span className="text-sm">Task Extractor</span>
          </button>
          <button className="w-full flex items-center gap-3 p-3 text-[#2c2f31] dark:text-slate-400 hover:shadow-[0_0_15px_rgba(0,101,118,0.3)] transition-all font-['Plus_Jakarta_Sans'] font-semibold">
            <span className="material-symbols-outlined">science</span>
            <span className="text-sm">Research Assistant</span>
          </button>
        </div>
        <div className="mt-auto pt-6 border-t border-surface-container-highest">
          <h5 className="text-xs font-bold mb-4 px-2">Quick Actions</h5>
          <button className="w-full bg-on-surface text-surface py-3 rounded-xl text-sm font-bold flex items-center justify-center gap-2 mb-3">
            <span className="material-symbols-outlined text-lg">upload_file</span>
            Analyze Resume
          </button>
          <button className="w-full border border-primary/20 text-primary py-3 rounded-xl text-sm font-bold flex items-center justify-center gap-2 hover:bg-primary/5 transition-all">
            Launch Full Workspace
          </button>
        </div>
      </div>
    </div>
  );
}
